services:
  soapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: SOAPI
    # restart: unless-stopped
    environment:
      - APP_ENV=production
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=mysecurepassword
    volumes:
      - ./samples:/app/samples
    ports:
      - "5001:5000"
    depends_on:
      neo4j:
        condition: service_healthy
        restart: true
    networks:
      - app_network

  neo4j:
    image: neo4j:2025.02.0-community-bullseye
    container_name: neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/mysecurepassword
    ports:
      - "7474:7474" # Web UI
      - "7687:7687" # Bolt Protocol
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:7474"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
